#!/usr/bin/awk -f
BEGIN {
	split(names, nameArray, ",")
}
/[0-9]\)/ {
	x = 0
	for (i in nameArray) {
		if($0 ~nameArray[i]) {
			x = 1
		}
	}
	if (x == 0) {
		print $0
	}
}
/\-/ {
	if (x != 1) {
		print $0
	}
}  
